### ISSUE TITLE
"Expected a boolean but was NUMBER" when "client.user().getName()"

### ISSUE THREAD

**Issue by Tickeldi** [tumblr/jumblr#107]
As the title says the following simple code throws an exception:
```
    public static void main( String[] args )
    {
    	// Authenticate via OAuth
    	JumblrClient client = new JumblrClient(
    	  "[my consumer key]",
    	  "[my consumer secret]"
    	);
    	client.setToken(
    	  "[my oauth token]",
    	  "[my oauth verifier]"
    	);

    	// Make the request
    	User user = client.user();
    	System.out.println(user.getName());
    	
    }
```

And I know why it does that. Here is part of an answer to an api request about my main user:

>         {
>           "admin": true,
>           "ask": true,
>           "ask_anon": true,
>           "ask_page_title": "Ask me anything",
>           "can_send_fan_mail": false,
>           "can_subscribe": false,
>           "description": "",
>           "drafts": 0,
>           "facebook": "N",
>           "facebook_opengraph_enabled": "N",
>           "followed": false,
>           "followers": 45,
>           "is_adult": false,
>           "is_blocked_from_primary": false,
>           "is_nsfw": false,
>           "messages": 17,
>           "name": "hinterdireindreikoepfigeraffe",
>           "placement_id": "",
>           "posts": 56,
>           "primary": false,
>           "queue": 0,
>           "reply_conditions": 3,
>           "share_likes": false,
>           "subscribed": false,
>           "title": "Hinter dir, ein dreiköpfiger Affe!",
>           "total_posts": 56,
>           "tweet": "N",
>           "twitter_enabled": false,
>           "twitter_send": false,
>           "type": "public",
>           "updated": 1491839017,
>           "url": "http://hinterdireindreikoepfigeraffe.tumblr.com/"
>         },
>         {
>           "admin": true,
>           "ask": 1,
>           "ask_anon": true,
>           "ask_page_title": "Ich weiß es doch auch nicht.",
>           "can_send_fan_mail": false,
>           "can_submit": true,
>           "can_subscribe": true,
>           "description": "Inkohärentes Geschreibe von einem offensichlich verrückten Mädchen, das ich NICHT kenne. Sie begann vor einem halben Jahr Nachrichten an meinen Blog \"knusprig-titten-hitler.tumblr.com\" zu schreiben und tut das auch heute noch ;)\n\nIch veröffentliche zwei Nachrichten jeden Tag.\n\nEine kleine Hilfe für alle, die nur DENKEN sie wären verrückt.",
>           "drafts": 0,
>           "facebook": "N",
>           "facebook_opengraph_enabled": "N",
>           "followed": false,
>           "followers": 24,
>           "is_adult": false,
>           "is_blocked_from_primary": false,
>           "is_nsfw": false,
>           "messages": 7,
>           "name": "shejustneverstoppedwriting",
>           "placement_id": "",
>           "posts": 165,
>           "primary": false,
>           "queue": 0,
>           "reply_conditions": 1,
>           "share_likes": false,
>           "submission_page_title": "Einreichen",
>           "submission_terms": {
>             "accepted_types": [
>               "text",
>               "photo",
>               "quote",
>               "link",
>               "video"
>             ],
>             "tags": [],
>             "title": "Einreichen",
>             "guidelines": ""
>           },
>           "subscribed": false,
>           "title": "She Just Never Stopped Writing",
>           "total_posts": 165,
>           "tweet": "N",
>           "twitter_enabled": false,
>           "twitter_send": false,
>           "type": "private",
>           "updated": 1375960847,
>           "url": "http://shejustneverstoppedwriting.tumblr.com/"
>         },

Look at the field for "ask".
At the first blog its
>           "ask": true,
At the second blog its
>           "ask": 1,
In some of my blogs the value of "ask" is 1. gson then crashes understandably because it tries to put an integer into a boolean field.
This seems to be a problem with the tumblr api. Any idea why that happens?

**Comment by ceyko** [comment]
@Tickeldi thanks for the bug report! We're looking into fixing this on the backend.

**Comment by melliott716** [comment]
Note I get this exact same error on a client.blogInfo() call for SOME followed blogs (again for the field **ask**).

**Comment by ceyko** [comment]
@Tickeldi @melliott716 We have fixed this on the backend. Let me know if you're still seeing issues.
