### ISSUE TITLE
Note info

### ISSUE THREAD

**Issue by amyngyn** [tumblr/jumblr#20]
I'm not sure if I'm missing something, but I don't see a way to get the notes associated with a post, even if we pass in true for the "notes_info" parameter. Please let me know if this is possible. Thank you!

**Comment by lakipn** [comment]
How to set `notes_info` parameter, so I could get notes of exactly one blog post? I'm using `client.blogPost( blogName, postId )` method to get the blog post. Currently, I'm getting null value every time I try to get notes using `post.getNotes()` method. Method `post.getNoteCount()` works.
