### ISSUE TITLE
Incompatible with Proguard?

### ISSUE THREAD

**Issue by jmrboosties** [tumblr/jumblr#46]
`W/System.err﹕ java.lang.ClassCastException: com.google.c.b.v cannot be cast to com.tumblr.jumblr.types.Blog
at com.tumblr.jumblr.types.User.getBlogs(SourceFile:63)`

This error is thrown when trying to perform `user.getBlogs()`

Initially, I couldn't even do `client.getUser()` until I added jumblr as a package to keep in the proguard settings file.

I stepped through the `getBlogs()` method and the data inside the list of blogs was correct, it just threw this when the method attempted to iterate through the list with a foreach loop.

**Comment by KevinTCoughlin** [comment]
Closing this as it appears to be a Proguard configuration issue. If you have a reproducible build, feel free to re-open and we'll take a look.
