### ISSUE TITLE
EXCEPTION FAILED TO EXECUTE GOAL ORG.CODEHOUSE

### ISSUE THREAD

**Issue by RushanArshad** [tumblr/jumblr#54]
my build stopped by giving an exception Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project jumblr: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]  can anyone help me in this?

**Comment by KevinTCoughlin** [comment]
@RushanArshad are you still having this build issue? It seems like more of a Maven configuration issue than problem with the library. Could you provide more details if the error is still occurring?
