### ISSUE TITLE
Is it possible to get total_posts of post list?

### ISSUE THREAD

**Issue by alphalin** [tumblr/jumblr#58]
Hi,
I can't find a method to get total_posts.
For example, I have a blog has 37 posts in total.
13 posts have tag "travel".
I use blogPosts(String blogName, Map<String,?> options) to get posts with tag "travel" and the limit sets to 5.
I can count List<Post> to get 5, but can't get the total_posts which should be 13.
Please help to make an enhancement.
Thanks.

**Comment by KevinTCoughlin** [comment]
Hey @alphalin, there is a method on the blog object that returns the total number of posts called `getPostCount()`. But for your use case I think you need to pass the offset as a query string parameter. You'll make the initial call and then use the returned size of the collection as the offset for subsequent requests. I'll work on providing a code snippet.

**Comment by alphalin** [comment]
Hi @KevinTCoughlin, I know the getPostCount() can get total posts of a blog but I can't find any input parameters I can use for my query in this method from document. It is great if you can provide a code snippet.

**Comment by KevinTCoughlin** [comment]
@alphalin something like this should work, but I would be a good citizen with its implementation. It can result in a large number of requests depending on the blog's post count.

```java
final Blog blog = client.blogInfo("your-blog.tumblr.com");
final int postCount = blog.getPostCount();
final List<Post> posts = new ArrayList<Post>();
int offset = 0;
while (offset < postCount) {
    final Map<String, Object> params = new HashMap<String, Object>();
    params.put("offset", offset);
    final List<Post> newPosts = client.blogPosts("your-blog.tumblr.com", params);
    posts.addAll(newPosts);
    offset += newPosts.size();
}
posts.size();
```

The implementation is as follows:
- Retrieve the total number of posts for a specific blog
- Initially begin with an offset of `0`, so I start at the most recent post
- I fetch the the most recent posts, returning a max of `20`
- I add the size of the fetched posts to my `offset`
- I loop until my `offset <= postCount` signaling that I've fetched all posts.

**Comment by alphalin** [comment]
@KevinTCoughlin thanks for the code snippet. as you said, it requests API many times inefficiently. is it possible to get total_posts directly from response rather than counting it one by one? Tumblr did provide total_posts in the API response. (refer to https://www.tumblr.com/docs/en/api/v2#posts )

**Comment by KevinTCoughlin** [comment]
@alphalin, the following returns total post count for a given blog.

```java
final Blog blog = client.blogInfo("your-blog.tumblr.com");
final int postCount = blog.getPostCount();
```

**Comment by alphalin** [comment]
@KevinTCoughlin `blog.getPostCount()` is total posts of a blog, not total posts for specific query (e.g., tag=travel). you can see my first comment for example.

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin blog.getPostCount() is total posts of a blog, not total posts for specific query (e.g., tag=travel). you can see my first comment for example.

Not currently, you'll have to do something similar to what I had above:
- Iterate over the posts returned for a given tag
- Append to a total posts `List` or increase a counter by the number returned 
- When the size of the posts returned is less than the limit you set or the default of `20` you have the total count of posts for that tag.
