### ISSUE TITLE
Is there a way to get ALL notes for a post?

### ISSUE THREAD

**Issue by utybo** [tumblr/jumblr#72]
I am writing a program that *needs* to access all notes for a post. After getting them, it gets rid of likes and reblogs that are not by blogs the user is interested in, and then uses the extracted reblogs to get a kind of "conversation" view of all the reblogs. 

Unfortunately, tumblr's API seems to limit the total number of notes that can be retrieved, and that there is no way to get *all* notes for a post. I hope I am wrong though.

So my question is : is there a way to easily retrieve _all_ notes of a post or, at least, _all_ notes from specific blogs?

**Comment by KevinTCoughlin** [comment]
@utybo unfortunately retrieving all notes for a post / blog is not currently supported by the tumblr API.
