### ISSUE TITLE
Can't get info out of userDashboard()

### ISSUE THREAD

**Issue by CodosaurusRex** [tumblr/jumblr#73]
Hi! Thanks for writing Jumblr it's awesome. I'm trying implement an android application that can display my dashboard- trying to get information out of the posts on my dash. However, when I try to do getType(), an empty string is returned. Is that a problem with my code, or Jumblr?

Thanks so much.

        JumblrClient client = new JumblrClient(consumerKey, consumerSecret); 
        client.setToken(oAuthToken, oAuthSecret);
        List<Post> posts = client.userDashboard();
        for (int i = 0; i < posts.size(); i++){
        Post post = (Post) posts.get(i);
        String postStr = post.toString();
        Log.e("Post Type", post.getType());
        Log.e("Author", post.getAuthorId());

**Comment by ericleong** [comment]
I can't seem to reproduce the issue using your code (with a few syntax corrections). Does this happen with all posts? Are the other fields empty too (like `id`)?

**Comment by CodosaurusRex** [comment]
Thanks for getting back to me! It was a mistake on my part- was unaware that I was filtering the LogCat, and missed the correct entries. Cheers!

**Comment by CodosaurusRex** [comment]
Sorry- one more question about Jumblr. Is there any way we can store com.tumblr.jumblr.types.Resource in an intent?

**Comment by ericleong** [comment]
> Sorry- one more question about Jumblr. Is there any way we can store com.tumblr.jumblr.types.Resource in an intent?

You'll need to write your own `Parcelable` class, since jumblr is just a Java library that doesn't know about Android.
