### ISSUE TITLE
Can someone help me about this error?

### ISSUE THREAD

**Issue by JosephusChou** [tumblr/jumblr#88]
Use Jumblr to develop an android app.
I got token and secret successfully, and I can get my following blogs' infos.
But the logcat output some error:
 E/NativeCrypto: ssl=0x7f58062880 cert_verify_callback x509_store_ctx=0x7f62ebed78 arg=0x0
E/NativeCrypto: ssl=0x7f58062880 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA

**Comment by KevinTCoughlin** [comment]
@JosephusChou are you sure that's an error? Looks like its just output from Android's native crypto lib on establishing SSL

**Comment by JosephusChou** [comment]
@KevinTCoughlin I'm a newbie about SSL and OAUth, so I'm not clear about that, maybe I should learn more about SSL

**Comment by bdenney** [comment]
@JosephusChou I think @KevinTCoughlin is right here, according to [this StackOverflow post](http://stackoverflow.com/questions/32074949/android-security-with-https-and-ssl-unknown-certificate-authority-nativecr) this is normal for some devices.

If you start getting errors from Jumblr, please reopen a different issue!
