### ISSUE TITLE
PhotoPost by source url don't get saved in "queued" state

### ISSUE THREAD

**Issue by Tickeldi** [tumblr/jumblr#89]
Hey. I am not sure what I am doing wrong here. Everything works fine except that my posts are getting saved in a published state instead of queued. No exceptions are thrown.

This is my method.
```
public void postImage(String imageSource, String text) throws IOException {
  try {
			PhotoPost post = clientToPostWith.newPost(
					blogname, 
					PhotoPost.class);
			post.setCaption(text);
			post.setState("queued");
			post.setPhoto(new Photo(imageSource));
			post.save();
			System.out.println(post.getState());
			System.out.println(clientToPostWith.blogPost(blogname, post.getId()).getState());
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		} catch (InstantiationException e) {
			e.printStackTrace();
		}
	}
}
```

The output is:

```
queued
published
```

**Comment by Tickeldi** [comment]
setState("draft")
and
    setState("private")
and of course
    setState("published")

do what they should do. The posts end up being a draft, private or published but never queued which, coincidentally, is the only state I am interested in :(

**Comment by Linus12** [comment]
Interesting. I do pretty much the same and it works fine for me. In fact when testing, I post to the queue, then in "production" I post to "published". There are a few differences though. I just reviewed where I create the post and I use:

    PhotosetPost psp = jClient.newPost(blogname, PhotosetPost.class);

The only difference, supposedly, between PhotoPost and a PhotosetPost is that with a PhotosetPost you can post more than one photo. But the differences in the classes is that Photoset just extends the PhotoPost with three additional interfaces: addPhoto, addSource, addData.

In my case the PhotosetPost is surrounded by a try/catch but I catch all exceptions, i.e.:

    PhotosetPost psp;
    try {
        psp = jClient.newPost(blogname, PhotosetPost.class);
     } catch (Exception e){
      ...

and the save is surrounded by the try catch as follows:

    try {
        psp.save();
    } catch (IOException e) {
        ...
    }
    catch (JumblrException j) {
        ...
    }

in my case though this is done because the creation and adding of fields and the final saving is done in different parts of the code.

it *shouldn't* make any difference, but does it work with a PhotosetPost?

**Comment by Tickeldi** [comment]
The location of the exceptions shouldn't make a difference really as they don't get thrown but you said so yourself. :)

I tried your suggestion but sadly, the symptoms remain the same. Any post where the state is set to "queue" goes online as "published".

Here is the code at the moment with your suggestion:

```
	public Poster() {
		clientToPostWith = new JumblrClient(CONSUMER_KEY, CONSUMER_SECRET);
		clientToPostWith.setToken(OAUTH_TOKEN, OAUTH_TOKEN_SECRET);
		
		blogname = clientToPostWith.user().getName();
	}
	
	public void postImage(String imageSource, String text) throws IOException {
		try {
			PhotosetPost post = clientToPostWith.newPost(
					blogname, 
					PhotosetPost.class);
			post.setCaption(text);
			post.setState("queued");
			post.addSource(imageSource);
			post.save();
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		} catch (InstantiationException e) {
			e.printStackTrace();
		}
	}
```

I included the constructor in case I do something wrong there. But authentication, connection etc doesn't seem to be an issue. It is really curious.

**Comment by Linus12** [comment]
OK, Just a really, really stupid, non technical, question here. How many entries do you currently have in your Tumblr Queue?

**Comment by Tickeldi** [comment]
47 which I pushed over there by hand from my drafts

**Comment by Tickeldi** [comment]
@Linus12 can I ask you, what version of Java you are using? And I assume you're using jumblr release 0.11?

**Comment by Linus12** [comment]
@Tickeldi currently using Java version: 1.8.0_73
As for Jumblr, I pulled down the current master source, which includes 0.11 plus a few additional fixes (like #80 and it's duplicate #79). I then made the changes as specified in my three pull requests (#71, #74, and #85). I then compile it into a .jar file that I use on my projects. Hopefully, sometime soon, version 12 will be released with at least these changes in it and I won't have to do this anymore.

But changes I made shouldn't have any affect on the state of a post.

Have you tried debugging and verifying a) the actual state just prior to the save, as well as the return response from the save? I had to do this to figure out some obscure error/warning messages that were never returned by Jumblr (or were so obfuscated that the actual error was "lost in translation").

**Comment by Tickeldi** [comment]
I'm using java version "1.8.0_74" on linux. I'm also using gson 2.5 but this shouldn't have an influence on jumblr really.
I tried debugging this yes and as far as I can follow the code the request is built just fine with "state=queued". I don't really understand the oauth step where the request gets translated into some kind of bytecode but I can't imagine that any of this contains the reason for the strange behaviour I am experiencing (can't be sure though). The response of a try run I just made was `{"meta":{"status":201,"msg":"Created"},"response":{"id":139820754791}}`. What I'll do right now is creating a minimal project containing just my problem with hardcoded values (not the token and secrets but everything else) and upload it to github. If that yields another result I'll have to have a look at my setup. If it doesn't maybe you or someone else can try to run it as well and see what happens.

**Comment by Tickeldi** [comment]
Here. https://github.com/Tickeldi/jumblrError. Libraries are included.
One class, one method, a main in Poster.java. It will create a post, write the local and remote state of it to stdout and delete the post again.
For me the output is
'''
Lokal state: queued
Remote state: published
'''

**Comment by bdenney** [comment]
Can you try setting the state to `queue` instead of `queued`?

According to the API docs for the `state` field:

> The state of the post. Specify one of the following:  published, draft, queue, private

**Comment by Tickeldi** [comment]
Thanks. I feel like an idiot. Firstly, I oriented myself at the actual tumblr api, thinking that the states would be the same here:
> States are published, queued, draft and private

And I did not look closely enough at the api-docs. Also I am sure I tried this before and it didn't work. Maybe I did something else wrong at that time because NOW it WORKS.

THANK YOU

**Comment by bdenney** [comment]
No worries, I'm glad it works for you now!
