### ISSUE TITLE
The number following

### ISSUE THREAD

**Issue by JasonLiuOrg** [tumblr/jumblr#90]
Hi,  I am using your ‘jubmlr’ api to develop an app.  When I use the method (‘userFollowing’) to get the blogs what I am following, the number of the blogs isn't equal to my account’following. My account’s following is 228, but the number I got from the ‘jubmlr’ is 20. So is there any limitation to the api?

**Comment by iwuvhugs** [comment]
To get the amount of blog use 
`user.getFollowingCount();`
It works for me properly (I have more than 20 blogs following)

**Comment by JasonLiuOrg** [comment]
@iwuvhugs Thank You. Your answer solved my problem.
