### ISSUE TITLE
How to post video using this library

### ISSUE THREAD

**Issue by mittalharsh54** [tumblr/jumblr#96]
how can we share video as i cant see any parameter in VideoPost class to share video.

**Comment by ceyko** [comment]
@mittalharsh54 you can use `setData()`. Pass it a `File`, and when you `save()` the post, it will be uploaded.

**Comment by mittalharsh54** [comment]
I gave tried that way but video post is not displayed in tumblr
Here is my code
`  VideoPost videoPost;
                try {
                    videoPost = client.newPost(client.user().getName(), VideoPost.class);
                    videoPost.setCaption("title");
                    videoPost.setData(new File(image_url));
                    videoPost.save();
                } catch (IllegalAccessException e1) {
                    // TODO Auto-generated catch block
                    e1.printStackTrace();
                } catch (InstantiationException e1) {
                    e1.printStackTrace();
                } catch (IOException e1) {
                    e1.printStackTrace();
                } 
`
